### PR TITLE
Regenerating atrium-api and Dirty Fixing label/defs

### PR DESCRIPTION
**Pull request by Sanhajio**
I don't think I have implemented the right solution.

### CODE REVIEW

**Comment by Sanhajio** [comment]
The main issue here is I manually added a change to a generated file I guess.

**Review by sugyan — CHANGES_REQUESTED** [review]
@Sanhajio Thanks for the fix suggestions! I have submitted the `codegen` fix to your repository, can you merge it?
https://github.com/Sanhajio/atrium/pull/1

**Comment by Sanhajio** [comment]
It's weird, I get this change when I regen:

```bash
  diff --git a/atrium-api/src/com/atproto/server/describe_server.rs b/atrium-api/src/com/atproto/server/describe_server.rs
  index 392ed1f..5472bf4 100644
  --- a/atrium-api/src/com/atproto/server/describe_server.rs
  +++ b/atrium-api/src/com/atproto/server/describe_server.rs
  @@ -5,9 +5,6 @@
   pub struct Output {
       ///List of domain suffixes that can be used in account handles.
       pub available_user_domains: Vec<String>,
  -    ///Contact information
  -    #[serde(skip_serializing_if = "Option::is_none")]
  -    pub contact: Option<Contact>,
       pub did: crate::types::string::Did,
       ///If true, an invite code must be supplied to create an account on this instance.
       #[serde(skip_serializing_if = "Option::is_none")]
  @@ -24,12 +21,6 @@ pub struct Output {
   pub enum Error {}
   #[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
   #[serde(rename_all = "camelCase")]
  -pub struct Contact {
  -    #[serde(skip_serializing_if = "Option::is_none")]
  -    pub email: Option<String>,
  -}
  -#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
  -#[serde(rename_all = "camelCase")]
   pub struct Links {
       #[serde(skip_serializing_if = "Option::is_none")]
       pub privacy_policy: Option<String>,
```

**Comment by sugyan** [comment]
Thanks for merging!
The change in describe_server.rs is due to the most recent lexicon change, and the current state of your branch should be correct.

**Review by sugyan — APPROVED** [review]

**Pull request merged**
