### PR TITLE
refactor: remove async_trait crate due to increased MSRV

### PR DESCRIPTION
**Pull request by oestradiol**
This PR is due to #233 and should only be merged after that one is merged

### CODE REVIEW

**Comment by oestradiol** [comment]
I wonder if there's a better way to do this without having to repeat the method definitions for every async trait method. I'm not particularly fond of that, but it seems that you cannot add a `#[cfg]` directive inside a definition...
However I imagine there's good reason for the `Send` trait to be relaxed for `wasm`, so I decided to keep it like it was to avoid breaking changes. 
@sugyan, if it is okay for me to ask why exactly is it done like that? Is there any specific difference on how Rust handles that on `wasm`?

**Comment by sugyan** [comment]
I don't know much about it, but I understand that JsValue is not-`Send`, so `wasm_bindgen` can't make it `Send`, and we need to switch it with `target_arch`, as in the current implementation.
ref: https://github.com/rustwasm/wasm-bindgen/issues/2833

So I'm wondering if we could do something similar by using the `trait-variant` crate (I haven't implemented and tested it properly yet.)
https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html#async-fn-in-public-traits
https://crates.io/crates/trait-variant

Since there should be no need to have both a `Send`able version and not, I think atrium could still be implemented using target_arch, with Send only when it is not wasm32, as follows.

```
#[cfg_attr(not(target_arch = “wasm32”), trait_variant::make(Send))]
```

**Comment by oestradiol** [comment]
[Force-pushed](https://github.com/sugyan/atrium/compare/5d6c33a35219e558145e8d2e6406a4fab8c4303b..4a9a4de2bc43c3664c9178184f4667562cc44f63) to resync the branch with #233.

**Comment by oestradiol** [comment]
Force-pushed [again](https://github.com/sugyan/atrium/compare/4a9a4de2bc43c3664c9178184f4667562cc44f63..2bcdbbb87c0654b69b977bd59f487f56780f9904) to re-do the commit for the wasm implementation, and [again](https://github.com/sugyan/atrium/compare/2bcdbbb87c0654b69b977bd59f487f56780f9904..4d45c41df16c352f3917366453ae2a3fe0f00c20) to format it.

@sugyan your suggestion worked wonderfully, `trait-variant` is really nice! I expanded the macros with [`cargo-expand`](https://github.com/dtolnay/cargo-expand) and it did exactly what we needed. The only issue happened on [`send_xrpc`](https://github.com/sugyan/atrium/pull/234/files#diff-6320a4f24102e693eaaa852fc7d50062ec9a5597d90b406bd4374d21076a61d5R49). `Self` has to be `Sync`, and unfortunately Rust does not support `#[cfg]` on `where` clauses 😢. I don't know if there's much we can do about this one, though. But it shouldn't be a big problem considering that I refactored out the default implementation to an external method, which means that any wrong change to the signature of `send_xrpc` in `XrpcClient` should cause a compile-time error.

**Comment by sugyan** [comment]
It was nice to have a cleaner code!

As for `send_xrpc`, sure... As for methods that provide default implementations like this, I guess I'll have to treat them specially. I think your current implementation seems good enough.

**Comment by oestradiol** [comment]
Ok! I'll turn this into a proper PR when #233 is merged then.

**Pull request merged**
